name: Preview
on:
  issue_comment:
    types: [created]
jobs:
  preview:
    name: preview
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/preview')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Preview
        run : |
          yarn add @redocly/cli@latest
          yarn run redocly bundle test.json --output "${{ github.sha }}.html"
          ENCODED_CONTENT="$(base64 -w 0 "${{ github.sha }}.html")"
          echo '{"message":"preview ${{ github.sha }}","content":"'"$ENCODED_CONTENT"'","branch":"gh-pages"}' >payload.json
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
            -T payload.json \
          "https://api.github.com/repos/Oreoxmt/docs/contents/${{ github.sha }}.html"