name: Prevent Deletion

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: echo
        run: |
          echo $pr
        env:
          pr: ${{ toJson(github) }}
      - name: Check changes
        run: |
          git diff --name-only --diff-filter 'D' '${{ github.event.pull_request.base.sha }}' '${{ github.event.pull_request.head.sha }}' | grep -E '^media/.*(jpg|png|jpeg)$' > /tmp/changed_files
          if [[ "$?" == "0" ]]; then
            cat /tmp/changed_files
            echo '{"name":"Image Deletion Check","head_sha":"${{ github.event.pull_request.head.sha }}","status":"completed","conclusion":"failure","output":{"title":"Image Deletion Check Report","summary":"tt","text":""}}' > /tmp/body.json
          else
            echo '{"name":"Image Deletion Check","head_sha":"${{ github.event.pull_request.head.sha }}","status":"completed","conclusion":"success","output":{"title":"Image Deletion Check Report","summary":"tt","text":""}}' > /tmp/body.json
          fi
      - name: Create a check run
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            'https://api.github.com/repos/${{ github.repository }}/check-runs' \
            -T '/tmp/body.json'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
