name: Preview
on:
  issue_comment:
    types: [created]
jobs:
  preview:
    name: preview
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/preview')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Preview
        run : |
          yarn add redoc-cli
          yarn run redoc-cli bundle test.json --output "${{ github.event.issue.pull_request.head.sha }}.html"
          ENCODED_CONTENT="$(base64 -w 0 "${{ github.event.issue.pull_request.head.sha }}.html")"
          echo '{"message":"preview ${{ github.event.issue.pull_request.head.sha }}","content":"'"$ENCODED_CONTENT"'","branch":"gh-pages"}' >payload.json
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
            -T payload.json \
          "https://api.github.com/repos/Oreoxmt/docs/contents/${{ github.event.issue.pull_request.head.sha }}.html"
      - name: Comment
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
            https://api.github.com/repos/Oreoxmt/docs/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"@${{ github.triggering_actor }} Preview link is [here](https://Oreoxmt.github.io/docs/${{ github.event.issue.pull_request.head.sha }}.html)"}'