name: Preview
on:
  issue_comment:
    types: [created]
jobs:
  preview:
    name: preview
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/preview')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Preview
        run : |
          yarn add @redocly/cli@latest
          redocly bundle test.json --output ${{ github.sha }}.html
