name: Prevent Deletion

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        run: |
          echo $pr
        env:
          pr: ${{ toJson(github) }}
      - name: Check changes
        run: |
          CHANGED_FILES=$(git diff --name-status --diff-filter 'D' ${{ github.pull_request.head.sha }} ${{ github.pull_request.base.sha }})
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
