name: Prevent Deletion

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: echo
        run: |
          echo $pr
        env:
          pr: ${{ toJson(github) }}
      - name: Check changes
        run: |
          git diff --name-only --diff-filter 'D' '${{ github.pull_request.head.sha }}' '${{ github.pull_request.base.sha }}' | grep -E '^media/.*(jpg|png|jpeg)$' > /tmp/changed_files.txt
          if [[ "$?" == "0" ]]; then
            # TODO: Changed
            echo /tmp/changed_files
          else
            # TODO: Not changed
            echo "No media "
          fi
